services:
  - type: web
    name: n8n-automacao
    env: docker
    plan: starter
    image: n8nio/n8n  # Adicione esta linha!
    healthCheckPath: /healthz
    envVars:
      - key: N8N_DEFAULT_BINARY_DATA_MODE
        value: filesystem
      - key: EXECUTIONS_PROCESS
        value: main
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
